# Generated by Django 4.1.2 on 2022-10-30 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proama', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Info',
        ),
    ]
